pub const MAP_1: &str = r#"
,\          o
o,\         o
oo,\        o
ooo|        o
oo`/    ^   o
oo|     |   o
o`/     |   o
`/      v   o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
|           o
|           o
|           o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
|           o
|           o
|           o
|           o
|           o
|           o
|           o
,\          o
o,\         o
oo|         o
oo|         o
oo|         o
oo|         o
o`/         o
`/          o
,\          o
ooooooooooooo
"#;